# Generated by Django 4.2.11 on 2024-04-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_image'),
        ('products', '0003_alter_products_brand'),
        ('product_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_product_shop', to='products.products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_shop_product', to='shop.shop', verbose_name='Магазин'),
        ),
    ]
