# Generated by Django 4.2.11 on 2024-04-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0002_alter_productprice_product_alter_productprice_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='new_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Новая цена'),
        ),
    ]
