# Generated by Django 5.0 on 2024-04-06 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_colours_options_alter_products_html_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название отзыва')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание отзыва')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('image', models.ImageField(blank=True, upload_to='media/feedback/%Y/%m/%d', verbose_name='Изображение')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='Отзыв о товаре')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['created_at'],
            },
        ),
    ]
