# Generated by Django 4.2.11 on 2024-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название магазина')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание магазина')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес магазина')),
                ('telephone', models.CharField(blank=True, max_length=100, verbose_name='Номер телефона')),
                ('coordinate_w', models.FloatField(blank=True, default=0, verbose_name='Коориданата по ширине')),
                ('coordinate_h', models.FloatField(blank=True, default=0, verbose_name='Коориданата по долгота')),
            ],
            options={
                'verbose_name': 'Магазины',
                'verbose_name_plural': 'Магазины',
                'ordering': ['created_at'],
            },
        ),
    ]
