# Generated by Django 4.2.11 on 2024-03-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/shops/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
