# Generated by Django 4.2.11 on 2024-04-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercart',
            options={'ordering': ['created_at'], 'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
    ]
