# Generated by Django 4.2.11 on 2024-04-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordercart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='ordercart',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер телефона'),
        ),
    ]
