# Generated by Django 4.2.11 on 2024-04-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordercart_fullname_ordercart_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес доставки'),
        ),
    ]
