# Generated by Django 5.0 on 2024-04-06 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colours',
            options={'ordering': ['created_at'], 'verbose_name': 'Цвета', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterField(
            model_name='products',
            name='html_color',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='products.colours', verbose_name='Цвет'),
        ),
    ]
