# Generated by Django 4.2.11 on 2024-04-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_colours_options_alter_products_html_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='products.brand', verbose_name='Бренд>'),
        ),
    ]
